### ISSUE TITLE
CoordsChar broken after scrolling in page

### ISSUE THREAD

**Issue by RobertDiebels** [codemirror/CodeMirror#4104]
I'm encountering and issue with coordsChar();

**Context**
I use  `codeMirrorInstance.getWrapperElement().onmousedown(callback())` to register clicks in the editor. After this I use coordsChar with the information from the onmousedown event to check if I'm clicking a bit of marked text.

If I'm clicking a bit of marked text I proceed with some actions.

This works fine only when I have not scrolled down. If I scroll down I get different a lineNumber than before. If I scroll back up until I can no longer scroll I get the correct lineNumber again (the one from the line I'm clicking).

**Steps**
Step 1: Create a CodeMirror editor somewhere on a webpage.
Step 2: Ensure the height of the page is larger than the window height (this will cause a scrollbar to appear). Ensure the editor is fully visible.
Step 3: Click on a line, coordsChar() will show you the correct lineNumber when printed.
Step 4: Scroll down.
Step 5: Click on the same line. It will no longer show the corect lineNumber.

**Result**
coordsChar() does not give the correct lineNumber after scrolling.

**Expected result**
I would expect that after scrolling the line I click still has the same lineNumber.

I've searched for a similar issue but I can't find one. Could you tell me if coordsChar accounts for scrolling in the webpage? Or if I need to use a specific mode.

**Comment by marijnh** [comment]
Did you notice the second argument to [`coordsChar`](http://codemirror.net/doc/manual.html#coordsChar)? If you're passing the event's `clientX` and `clientY` here, you'll want to pass `"window"`.

**Comment by RobertDiebels** [comment]
@marijnh Sorry for the late reply. It appears I missed your comment. I've tested this for all modes, ("page"/"window", "div", "local"/undefined) and the coords are consistently off.

I did some debugging and it appears that the browsers I've tested already correct the coords from the event by subtracting the scrollOffset. The code for coordsChar also does this so the offSet is subtracted twice. This causes codeMirror to conclude that I'm a few lines above where I'm clicking.

Browsers I've tested: Chrome (51.0.2704.103 m), Edge (25.10586.0.0, EdgeHTML 13.10586), FireFox (47.0.1), IE11 (11.212.10586.0).

The hotfix I implemented was adding the same offset Codemirror uses to the "top:" property of the object passed to coordsChar. Like so:

`        this.codeMirror.getWrapperElement().onmousedown = function ( e ) {
            var coords = {
                left: e.clientX,
                top:  e.clientY +  window.pageYOffset || (document.documentElement || document.body).scrollLeft
            };
            var lineCh = self.codeMirror.coordsChar(coords);
};
`
If I need to make a jsfiddle or anything please tell me. But I haven't found a website where I can provide an example bit of code which allow me to use  the whole page and make sure I have enough height to get a scrollbar.

**Comment by marijnh** [comment]
Your code example still isn't passing a second argument of `"window"` to `coordsChar`.

**Comment by RobertDiebels** [comment]
@marijnh I see what you mean now :). I though "window" was explicitly handled but it's just a fall through. Hence the mistake.
