### ISSUE TITLE
Cursor set to EOF when focusing with active line mismatch (inputStyle=contenteditable)

### ISSUE THREAD

**Issue by westonruter** [codemirror/CodeMirror#4975]
I'm noticing an issue whereby when you click on the editor to focus and set the cursor on a given line, it will focus but then put the cursor at the end of the editor without scrolling to that position. Sometimes it will even add the active-line style to where you clicked, but the cursor is at the bottom. Every time you blur the editor an then focus back into the editor, the cursor will get moved to the end of the file. The issue is happening only when `inputStyle` is set to `contenteditable`. When `inputStyle` is `textarea` the behavior is as expected.

Demos:
FAIL (inputStyle=contenteditable): https://youtu.be/uSFJqf_zwFw
PASS (inputStyle=textarea): https://youtu.be/CqMLObojkVU

WordPress core ticket: https://core.trac.wordpress.org/ticket/41900

**Comment by adrianheine** [comment]
I can somewhat reproduce that. If, when I click into the editor, the document didn't have focus, the cursor is positioned where it was when the document lost focus. That's different with `textarea`.

**Comment by adrianheine** [comment]
Quick investigation shows that in my case the selection is internally correctly updated, but the display is not updated afterwards.

**Comment by adrianheine** [comment]
`ContentEditableInput::showPrimarySelection` needs to be called. It is called from `ContentEditableInput::showSelection` if CodeMirror thinks it was focused before (`cm.state.focused`) or if `op.focus` is set (mainly happens in the `mousedown` event handler) to the currently active element and `document.hasFocus()` returns true. When clicking, this logic is executed twice, first on `mousedown` and second on `mouseup`. `cm.state.focused` is false at both times. On `mousedown`, `op.focus` is set, _but_, if the window had focus before, `document.hasFocus()` returns false. If the window didn't have focus before, `document.hasFocus()` returns true and `showPrimarySelection` is called. On `mouseup`, `document.hasFocus()` is true in both cases, but `op.focus` is not set.

I don't know if this is a browser bug, it definitely feels strange to me. @marijnh ehy do we need the `hasFocus()` check in `operations` in the first place? I think `op.focus` is only set in cases where we are pretty sure that we really really want to have the focus.

**Comment by marijnh** [comment]
@adrianheine I think the idea behind that test is to not muck with focus when the document isn't active. I added it specifically at some point (aebf68bf574bfc), but I can no longer figure out why (I don't appear to have closed any issues on that day). I agree that there's probably not much that can go wrong with focusing the editor when it receives key/mouse events, so feel free to remove it.

**Comment by adrianheine** [comment]
Ok, I'll do that. Btw, Webkit sets `hasFocus` already to true on `mousedown`. Probably a Firefox bug.

**Comment by adrianheine** [comment]
@westonruter Can you try current `master`?

**Comment by westonruter** [comment]
@adrianheine I'm not seeing any improvement. The same issue still happens in Chrome and Firefox.

I've spun up a test WordPress site with the latest `master` for CodeMirror (8f35a1a). I've created WP admin user accounts for both you and @marijnh to be able to see the issue firsthand. You should have received credentials via Git commit author details; your WordPress usernames same as on GitHub.

Direct URL to the WordPress core CSS editor which shows the issue: http://trac-41900-xwp-testbed.pantheonsite.io/wp-admin/customize.php?autofocus[section]=custom_css

In both Chrome and Firefox, the initial click into the editor causes the cursor to be set as active outside the viewport. A second click after the editor is already focuses causes the cursor to appear in the expected spot. In Firefox the initial editor focus click is causing the cursor to go to line 51, whereas in Chrome the initial click is causing the cursor to go to line 49.

Unminified JavaScript bundle for CodeMirror: http://trac-41900-xwp-testbed.pantheonsite.io/wp-includes/js/codemirror/codemirror.js?ver=5.29.1-alpha-8f35a1a

**Comment by adrianheine** [comment]
Ok, so apparently I fixed a different issue, thanks for pointing me in that direction, though. I can reproduce your issue in your instance in my Firefox.

**Comment by westonruter** [comment]
@adrianheine yes, I suspect it might have something to do with how CodeMirror is embedded in an element that has absolute positioning that was animated into place. But even if I have it defer initialization until after the container element has been fully animated into place, the problem persists.

**Comment by westonruter** [comment]
@adrianheine We found the problematic code ([props](https://core.trac.wordpress.org/ticket/41900#comment:7) @afercia):

```js
editor.on( 'focus', function( codemirror ) {
  editor.refresh();
});
```

Now, first of all we probably are going to remove this from WordPress, so we may not need to fix this issue for the sake of core, but nevertheless there would seem to be a bug in CodeMirror with calling the `refresh()` method when focusing on an editor that has a `inputStyle=contenteditable`.

Here is a minimal example: https://jsfiddle.net/westonruter/enf71znt/
